import React, { useState } from "react";
import { Button } from "@/components/ui/button";
import { Copy, Download, Check, Share2, Twitter, Linkedin, Link } from "lucide-react";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";

export default function ReportActions({ reportContent, ticker, recommendation, priceTarget, updownPct }) {
  const [copied, setCopied] = useState(false);
  const [linkCopied, setLinkCopied] = useState(false);

  const handleCopy = () => {
    navigator.clipboard.writeText(reportContent);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([reportContent], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${ticker?.replace(/\s+/g, "_") || "report"}_equity_research.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const shareText = () => {
    const updown = updownPct != null ? ` | ${updownPct >= 0 ? "+" : ""}${updownPct.toFixed(1)}% upside` : "";
    const target = priceTarget != null ? ` | PT: $${priceTarget}` : "";
    return `${ticker} — ${recommendation || "Analysis"}${target}${updown}\n\nGenerated by AI-Investor 📊`;
  };

  const handleShareTwitter = () => {
    const text = encodeURIComponent(shareText());
    window.open(`https://twitter.com/intent/tweet?text=${text}`, "_blank");
  };

  const handleShareLinkedIn = () => {
    const url = encodeURIComponent(window.location.href);
    const title = encodeURIComponent(`${ticker} Equity Research Report`);
    window.open(`https://www.linkedin.com/sharing/share-offsite/?url=${url}&title=${title}`, "_blank");
  };

  const handleCopyLink = () => {
    navigator.clipboard.writeText(window.location.href);
    setLinkCopied(true);
    setTimeout(() => setLinkCopied(false), 2000);
  };

  const handleNativeShare = () => {
    if (navigator.share) {
      navigator.share({
        title: `${ticker} Equity Research Report`,
        text: shareText(),
        url: window.location.href,
      });
    }
  };

  return (
    <div className="flex items-center gap-1.5">
      <Button variant="outline" size="sm" onClick={handleCopy} className="gap-1.5 h-8 text-xs border-border">
        {copied ? <Check className="h-3.5 w-3.5 text-emerald-400" /> : <Copy className="h-3.5 w-3.5" />}
        {copied ? "Copied!" : "Copy"}
      </Button>
      <Button variant="outline" size="sm" onClick={handleDownload} className="gap-1.5 h-8 text-xs border-border">
        <Download className="h-3.5 w-3.5" />
        Download
      </Button>
      <DropdownMenu>
        <DropdownMenuTrigger asChild>
          <Button variant="outline" size="sm" className="gap-1.5 h-8 text-xs border-border">
            <Share2 className="h-3.5 w-3.5" />
            Share
          </Button>
        </DropdownMenuTrigger>
        <DropdownMenuContent align="end" className="w-44">
          <DropdownMenuItem onClick={handleShareTwitter} className="gap-2 text-xs cursor-pointer">
            <Twitter className="h-3.5 w-3.5" />
            Share on X / Twitter
          </DropdownMenuItem>
          <DropdownMenuItem onClick={handleShareLinkedIn} className="gap-2 text-xs cursor-pointer">
            <Linkedin className="h-3.5 w-3.5" />
            Share on LinkedIn
          </DropdownMenuItem>
          <DropdownMenuSeparator />
          <DropdownMenuItem onClick={handleCopyLink} className="gap-2 text-xs cursor-pointer">
            {linkCopied ? <Check className="h-3.5 w-3.5 text-emerald-400" /> : <Link className="h-3.5 w-3.5" />}
            {linkCopied ? "Link copied!" : "Copy link"}
          </DropdownMenuItem>
          {typeof navigator !== "undefined" && navigator.share && (
            <DropdownMenuItem onClick={handleNativeShare} className="gap-2 text-xs cursor-pointer">
              <Share2 className="h-3.5 w-3.5" />
              More options…
            </DropdownMenuItem>
          )}
        </DropdownMenuContent>
      </DropdownMenu>
    </div>
  );
}